
let schedule={}, resources=[], settings={}, exams={}, subjectsData={};
let supabaseClient = null, currentUser=null, deferredPrompt=null;
let currentDate=localStorage.getItem("reviseflow_current_date");
let currentMonth=null, activeTab=localStorage.getItem("reviseflow_active_tab")||"home";
let currentSubject=null;
let supabase = null;
const completed=JSON.parse(localStorage.getItem("reviseflow_completed")||"{}");
const rag=JSON.parse(localStorage.getItem("reviseflow_rag")||"{}");
const themeStored=localStorage.getItem("reviseflow_theme")||"dark";
async function loadJson(path){ const r=await fetch(path); return await r.json(); }
async function loadData(){
  [schedule,resources,settings,subjectsData]=await Promise.all([loadJson("./schedule.json"),loadJson("./resources.json"),loadJson("./settings.json"),loadJson("./subjects.json")]);
  exams=settings.exams||{};
  document.title=settings.appName||"ReviseFlow v6";
  document.getElementById("appTitle").textContent=settings.appName||"ReviseFlow v6";
  if (settings.supabaseUrl && settings.supabaseAnonKey) {
  supabase = window.supabase.createClient
    settings.supabaseUrl,
    settings.supabaseAnonKey
  );
} supabase=window.supabase.createClient(settings.supabaseUrl, settings.supabaseAnonKey); }
  const today=new Date().toISOString().slice(0,10);
  if(!currentDate||!schedule[currentDate]) currentDate=schedule[today]?today:settings.startDate;
  currentMonth=currentDate.slice(0,7);
}
function saveLocal(){ localStorage.setItem("reviseflow_completed", JSON.stringify(completed)); localStorage.setItem("reviseflow_rag", JSON.stringify(rag)); localStorage.setItem("reviseflow_current_date", currentDate); localStorage.setItem("reviseflow_active_tab", activeTab); }
function clampDate(ds){ if(settings.startDate && ds<settings.startDate) return settings.startDate; if(settings.endDate && ds>settings.endDate) return settings.endDate; return ds; }
function prettyDate(ds){ return new Date(ds+"T12:00:00").toLocaleDateString(undefined,{weekday:"long",day:"numeric",month:"long",year:"numeric"}); }
function monthLabel(ym){ return new Date(ym+"-01T12:00:00").toLocaleDateString(undefined,{month:"long",year:"numeric"}); }
function taskId(ds,idx){ return ds+"__"+idx; } function isDone(ds,idx){ return !!completed[taskId(ds,idx)]; }
function setSyncStatus(t){ document.getElementById("syncStatus").textContent=t; } function setUserStatus(t){ document.getElementById("userStatus").textContent=t; }
async function setCompleted(ds,idx,value){ const id=taskId(ds,idx); completed[id]=value; saveLocal(); render(); if(currentUser&&supabase){ await supabase.from("progress").upsert({user_id:currentUser.id, task_id:id, completed:value}); setSyncStatus("Cloud synced"); } }
async function toggleDone(ds,idx){ await setCompleted(ds,idx,!isDone(ds,idx)); }
function setRag(subject,topic,level){ rag[subject+"__"+topic]=level; saveLocal(); renderSubjectsDetail(); } function getRag(subject,topic){ return rag[subject+"__"+topic]||"red"; }
function allDates(){ return Object.keys(schedule).sort(); }
function shiftDay(ds,n){ const d=new Date(ds+"T12:00:00"); d.setDate(d.getDate()+n); return clampDate(d.toISOString().slice(0,10)); }
function carryOverTasks(ds){ const items=[]; for(const d of allDates()){ if(d>=ds) break; (schedule[d]||[]).forEach((task,idx)=>{ if(!isDone(d,idx)) items.push({date:d,idx,task});});} return items.slice(-8); }
function examMeta(ds){ return exams[ds]||[]; }
function progressForDate(ds){ const tasks=schedule[ds]||[]; const done=tasks.filter((_,idx)=>isDone(ds,idx)).length; return {done,total:tasks.length,pct:tasks.length?Math.round(done*100/tasks.length):0}; }
function renderTaskList(container,items,mode="main"){ if(!items.length){ container.innerHTML='<div class="task">Nothing here right now.</div>'; return; } container.innerHTML=items.map((item,idx)=>{ const task=mode==="main"?item:item.task; const ds=mode==="main"?currentDate:item.date; const tIdx=mode==="main"?idx:item.idx; const done=isDone(ds,tIdx); return `<div class="task ${done?'done':''} ${mode==='carry'?'carry':''}"><div class="subject">${task.subject}</div><div class="taskTitle">${task.title}</div>${mode==='carry'?`<div class="miniLabel">From ${prettyDate(item.date)}</div>`:''}<div class="taskDetails">${task.details||''}</div><div class="taskActions"><button class="small" onclick="toggleDone('${ds}',${tIdx})">${done?'Untick':'Tick complete'}</button></div></div>`; }).join(""); }
function renderHome(){ const today=new Date().toISOString().slice(0,10); document.getElementById("homeDateTag").textContent=currentDate===today?"Today":"Selected day"; document.getElementById("homeDateTitle").textContent=prettyDate(currentDate); const ex=examMeta(currentDate), tasks=schedule[currentDate]||[], subjects=[...new Set(tasks.map(t=>t.subject))]; document.getElementById("homeMeta").innerHTML=`<span class="pill">${subjects.length} subjects</span><span class="pill">${ex.length?ex.length+' exam item'+(ex.length>1?'s':''):'Revision day'}</span>`; const p=progressForDate(currentDate); document.getElementById("progressText").textContent=`${p.done} of ${p.total} tasks done`; document.getElementById("progressFill").style.width=p.pct+"%"; renderTaskList(document.getElementById("todayTasks"), tasks, "main"); renderTaskList(document.getElementById("carryTasks"), carryOverTasks(currentDate), "carry"); document.getElementById("linksBox").innerHTML=resources.map(r=>`<div class="linkCard"><div class="subject">${r.name}</div><div class="taskTitle">${r.label}</div><a href="${r.url}" target="_blank">${r.url}</a></div>`).join(""); }
function renderCalendar(){ document.getElementById("monthTitle").textContent=monthLabel(currentMonth); const start=new Date(currentMonth+"-01T12:00:00"); const firstDow=(start.getDay()+6)%7; const gridStart=new Date(start); gridStart.setDate(start.getDate()-firstDow); const today=new Date().toISOString().slice(0,10); let cells=[]; for(let i=0;i<42;i++){ const d=new Date(gridStart); d.setDate(gridStart.getDate()+i); const ds=d.toISOString().slice(0,10); const ex=examMeta(ds), prog=progressForDate(ds); cells.push(`<button class="dayCell ${ds.slice(0,7)!==currentMonth?'other':''} ${ds===currentDate?'selected':''}" onclick="selectDate('${ds}')"><div class="dayNum">${d.getDate()}</div><div class="miniDots">${ex.length?'<span class="miniDot" style="background:var(--amber)"></span>':''}${(schedule[ds]||[]).length?'<span class="miniDot"></span>':''}${prog.total&&prog.done===prog.total?'<span class="miniDot" style="background:var(--green)"></span>':''}</div><div class="miniLabel">${ds===today?'Today':ex.length?'Exam':(schedule[ds]||[]).length?prog.done+'/'+prog.total:''}</div></button>`);} document.getElementById("calendarGrid").innerHTML=cells.join(""); document.getElementById("selectedDateTitle").textContent=prettyDate(currentDate); document.getElementById("selectedExamPills").innerHTML=(examMeta(currentDate).length?examMeta(currentDate).map(e=>`<span class="pill">${e.title}</span>`).join(""):'<span class="pill">No exam on this date</span>'); renderTaskList(document.getElementById("selectedTasks"), schedule[currentDate]||[], "main"); }
function renderSubjectsGrid(){ const grid=document.getElementById("subjectsGrid"); grid.innerHTML=Object.keys(subjectsData).map(name=>{ const s=subjectsData[name]; return `<div class="subjectCard" onclick="openSubject(${JSON.stringify(name)})"><div class="subject">${s.board}</div><h3>${name}</h3><div class="small">${(s.key_topics||[]).slice(0,3).join(" · ")}</div></div>`; }).join(""); }
function openSubject(name){ currentSubject=name; document.getElementById("subjectDetail").classList.remove("hidden"); renderSubjectsDetail(); showTab('subjects'); }
function renderSubjectsDetail(){ if(!currentSubject) return; const s=subjectsData[currentSubject]; document.getElementById("subjectTitle").textContent=currentSubject; document.getElementById("subjectBoard").textContent=s.board; document.getElementById("subjectKeyTopics").innerHTML=`<div class="subject">Key topics</div><div class="taskTitle">${(s.key_topics||[]).join(" · ")}</div>`; document.getElementById("subjectWebsites").innerHTML=`<div class="subject">Useful websites</div>${(s.websites||[]).map(w=>`<div class="taskTitle" style="font-size:.96rem">${w.label}</div><a href="${w.url}" target="_blank">${w.url}</a>`).join("")}`; const english=document.getElementById("englishExtras"); if(currentSubject==="English Literature"){ const e=s.english_sets||{}; english.classList.remove("hidden"); english.innerHTML=`<div class="subject">English extras</div>${Object.keys(e).map(book=>`<div class="quoteCard"><div class="taskTitle">${book}</div><div class="small"><strong>Themes:</strong> ${(e[book].themes||[]).join(", ")}</div><div class="small"><strong>Characters:</strong> ${(e[book].characters||[]).join(", ")}</div><div class="small"><strong>Key quotes:</strong> ${(e[book].quotes||[]).join(" | ")}</div></div>`).join("")}`; } else { english.classList.add("hidden"); english.innerHTML=""; } document.getElementById("subjectTopicsList").innerHTML=(s.topics||[]).map(topic=>{ const level=getRag(currentSubject,topic); return `<div class="topicCard"><div class="subject">${currentSubject}</div><div class="taskTitle">${topic}</div><div class="small">Set your confidence:</div><div class="topicToolbar"><button class="small rag-red ${level==='red'?'activeChoice':''}" onclick="setRag(${JSON.stringify(currentSubject)},${JSON.stringify(topic)},'red')">Red</button><button class="small rag-amber ${level==='amber'?'activeChoice':''}" onclick="setRag(${JSON.stringify(currentSubject)},${JSON.stringify(topic)},'amber')">Amber</button><button class="small rag-green ${level==='green'?'activeChoice':''}" onclick="setRag(${JSON.stringify(currentSubject)},${JSON.stringify(topic)},'green')">Green</button></div></div>`; }).join(""); }
function applyTheme(t){ document.body.setAttribute("data-theme", t); localStorage.setItem("reviseflow_theme", t); } function toggleTheme(){ applyTheme(document.body.getAttribute("data-theme")==="dark"?"light":"dark"); }
function selectDate(ds){ currentDate=clampDate(ds); currentMonth=currentDate.slice(0,7); saveLocal(); render(); }
function showTab(tab){ activeTab=tab; ["home","calendar","subjects","menu"].forEach(p=>document.getElementById(p+"Page").classList.toggle("active", p===tab)); ["home","calendar","subjects","menu"].forEach(p=>document.getElementById(p+"TabBtn").classList.toggle("active", p===tab)); saveLocal(); }
function showApp(){ document.getElementById("authView").classList.add("hidden"); document.getElementById("appView").classList.remove("hidden"); }
function showAuth(){ document.getElementById("authView").classList.remove("hidden"); document.getElementById("appView").classList.add("hidden"); }
function authMessage(msg){ const el=document.getElementById("authMessage"); el.classList.remove("hidden"); el.textContent=msg; }
async function loadCloudProgress(){ if(!currentUser||!supabase) return; setSyncStatus("Syncing..."); const {data,error}=await supabase.from("progress").select("task_id,completed").eq("user_id", currentUser.id); if(error){ setSyncStatus("Cloud sync error"); return; } (data||[]).forEach(r=>completed[r.task_id]=r.completed); saveLocal(); setSyncStatus("Cloud synced"); }
async function handleSession(){ if(!supabase){ showApp(); setSyncStatus("Local mode"); setUserStatus("No backend"); render(); return; } const {data}=await supabase.auth.getSession(); currentUser=data.session?.user||null; if(currentUser){ showApp(); setUserStatus(currentUser.email||"Signed in"); document.getElementById("logoutBtn").classList.remove("hidden"); await loadCloudProgress(); render(); } else showAuth(); }
async function signUp(){ const email=document.getElementById("emailInput").value.trim(), password=document.getElementById("passwordInput").value.trim(); const {error}=await supabase.auth.signUp({email,password}); authMessage(error?error.message:"Account created. If email confirmation is on, confirm it, then sign in."); }
async function signIn(){ const email=document.getElementById("emailInput").value.trim(), password=document.getElementById("passwordInput").value.trim(); const {error}=await supabase.auth.signInWithPassword({email,password}); if(error) authMessage(error.message); }
async function signOut(){ await supabase.auth.signOut(); currentUser=null; showAuth(); }
function bindUI(){ document.getElementById("todayBtn").onclick=()=>selectDate((schedule[new Date().toISOString().slice(0,10)]?new Date().toISOString().slice(0,10):settings.startDate)); document.getElementById("prevDayBtn").onclick=()=>selectDate(shiftDay(currentDate,-1)); document.getElementById("nextDayBtn").onclick=()=>selectDate(shiftDay(currentDate,1)); document.getElementById("homePrevBtn").onclick=()=>selectDate(shiftDay(currentDate,-1)); document.getElementById("homeNextBtn").onclick=()=>selectDate(shiftDay(currentDate,1)); document.getElementById("prevMonthBtn").onclick=()=>{ const d=new Date(currentMonth+"-01T12:00:00"); d.setMonth(d.getMonth()-1); currentMonth=d.toISOString().slice(0,7); renderCalendar(); }; document.getElementById("nextMonthBtn").onclick=()=>{ const d=new Date(currentMonth+"-01T12:00:00"); d.setMonth(d.getMonth()+1); currentMonth=d.toISOString().slice(0,7); renderCalendar(); }; document.getElementById("themeBtn").onclick=toggleTheme; document.getElementById("themeBtn2").onclick=toggleTheme; document.getElementById("homeTabBtn").onclick=()=>showTab("home"); document.getElementById("calendarTabBtn").onclick=()=>showTab("calendar"); document.getElementById("subjectsTabBtn").onclick=()=>showTab("subjects"); document.getElementById("menuTabBtn").onclick=()=>showTab("menu"); document.getElementById("closeSubjectBtn").onclick=()=>document.getElementById("subjectDetail").classList.add("hidden"); document.getElementById("guestBtn").onclick=()=>{ showApp(); setSyncStatus("Local mode"); setUserStatus("Signed out"); render(); }; document.getElementById("signUpBtn").onclick=signUp; document.getElementById("signInBtn").onclick=signIn; document.getElementById("logoutBtn").onclick=signOut; window.addEventListener("beforeinstallprompt",(e)=>{e.preventDefault(); deferredPrompt=e; document.getElementById("installBtn").classList.remove("hidden");}); document.getElementById("installBtn").onclick=async()=>{ if(!deferredPrompt) return; deferredPrompt.prompt(); await deferredPrompt.userChoice; deferredPrompt=null; document.getElementById("installBtn").classList.add("hidden"); }; if("serviceWorker" in navigator) navigator.serviceWorker.register("./sw.js").catch(()=>{}); if(supabase) supabase.auth.onAuthStateChange(async()=>{ await handleSession(); }); window.toggleDone=toggleDone; window.selectDate=selectDate; window.openSubject=openSubject; window.setRag=setRag; }
function render(){ renderHome(); renderCalendar(); renderSubjectsGrid(); if(currentSubject) renderSubjectsDetail(); showTab(activeTab); }
async function start(){ await loadData(); bindUI(); await handleSession(); applyTheme(themeStored); render(); }
start();
